# PHP CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-php/
version: 2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      # we don't need browsers, but this image contains java (needed to run OpenApiGenerator)
      - image: cimg/php:8.2.8-browsers

    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "symfony-server/composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: ./scripts/installDependencies.sh
      - save_cache:
          key: v1-dependencies-{{ checksum "symfony-server/composer.lock" }}
          paths:
            - ./symfony-server/vendor
      - run: chmod u+x ./scripts/runSymfonyTests.sh
      - run: ./scripts/runSymfonyTests.sh
