# PHP CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-php/
version: 2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      # we don't need browsers, but this image contains java (needed to run OpenApiGenerator)
      - image: cimg/php:8.2.8-browsers

    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run: ./scripts/installDependencies.sh
      - run: chmod u+x ./scripts/runSymfonyTests.sh
      - run: ./scripts/runSymfonyTests.sh
